name: Manage Repositories

on:
  schedule:
    - cron: '0 0 * * MON'  # Runs every Monday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  manage_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Run repository management script
        env:
          GTOKEN: ${{ secrets.GTOKEN }}
          GUSERNAME: ${{ secrets.GUSERNAME }}
        run: python manage_repos.py
