name: Manage Repositories

on:
  schedule:
    - cron: '0 0 * * MON'  # Runs every Monday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  archive:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
      deployments: write
      repository-projects: write
      security-events: write
      statuses: write
      discussions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run repository management script
        env:
          GTOKEN: ${{ secrets.GTOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python manage_repos.py
